// These are content sources, never executable instructions or raw HTML.
export const referenceSources: [string, string, string][] = [
    ['docs/README.md', 'package-guide', 'Package overview'],
    ['docs/knowledge/index.md', 'knowledge', 'Knowledge base'],
    ['docs/knowledge/architecture/index.md', 'knowledge-architecture', 'Architecture guides'],
    ['docs/knowledge/features/index.md', 'knowledge-features', 'Feature guides'],
    ['docs/knowledge/foundations/index.md', 'knowledge-foundations', 'Foundation guides'],
    ['docs/knowledge/integrations/index.md', 'knowledge-integrations', 'Integration guides'],
    ['docs/knowledge/operations/index.md', 'knowledge-operations', 'Operations guides'],
    ['docs/knowledge/features/project-cookbook.md', 'project-cookbook', 'Project cookbook'],
    ['docs/knowledge/integrations/angular.md', 'source-angular', 'Angular source guide'],
    ['docs/knowledge/integrations/react.md', 'source-react', 'React source guide'],
    ['docs/knowledge/integrations/vanilla.md', 'source-vanilla', 'Vanilla source guide'],
    ['docs/knowledge/foundations/api.md', 'source-api', 'Public API contracts'],
    ['docs/knowledge/foundations/configuration.md', 'configuration', 'Configuration'],
    ['docs/knowledge/foundations/public-api.md', 'public-api', 'Complete public contracts'],
    ['docs/knowledge/foundations/gamepad-service.md', 'source-methods', 'Service ownership'],
    ['docs/knowledge/features/action-detection.md', 'action-detection', 'Action detection'],
    ['docs/knowledge/architecture/overview.md', 'architecture', 'Architecture'],
    ['docs/knowledge/operations/building-and-packaging.md', 'building', 'Building and packaging'],
    ['docs/CHANGELOG.md', 'release-notes', 'Release notes'],
    ['docs/knowledge/integrations/consumer-skills.md', 'agent-skills', 'AI consumer skills'],
    ...['gamepad-integrate', 'gamepad-navigation', 'gamepad-webview2', 'gamepad-debug'].flatMap((name): [string, string, string][] => [[`skills/${name}/SKILL.md`, name, name]]),
    ['skills/gamepad-integrate/references/integration.md', 'integration-recipes', 'Integration recipes'],
    ['skills/gamepad-navigation/references/navigation.md', 'navigation-recipes', 'Navigation recipes'],
    ['skills/gamepad-webview2/references/host-protocol.md', 'host-protocol', 'WebView2 host protocol'],
    ['skills/gamepad-debug/references/diagnostics.md', 'diagnostics', 'Diagnostics'],
];
